config: null
dataset: csv_seg
data_root: data/
csv: dataset/merged/all_datasets_mobius_val.csv
default_format: mobius_3c
model: unet_se_small
img_size: 160
img_width: null
img_height: null
in_channels: 1
num_classes: 3
base: 32
batch_size: 16
epochs: 50
lr: 0.001
weight_decay: 0.0001
workers: 2
color: false
out: !!python/object/apply:pathlib.PosixPath
- runs
- unet_mobius_val_training_results
- 2026-02-19_00-30-42
val_every: 1
save_every: 0
resume: null
metrics_csv: null
metrics_plot: null
log_every: 0
save_best_metrics: false
tensorboard: false
show_examples: 0
show_examples_every: 1
